language: r

cache: packages

warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

before_install:
  - Rscript -e 'install.packages(c("roxygen2", "devtools", "irlba", "pkgconfig"))'
  - make

apt_packages:
  - libx11-dev
  - libglu1-mesa-dev
  - libfreetype6-dev
  - libxml2-dev
  - libgmp-dev

bioc_packages:
  - graph

r_github_packages:
  - hadley/lazyeval
  - igraph/igraphdata
  - gaborcsardi/pkgconfig

r_packages:
  - roxygen2
  - NMF
  - rgl
  - ape
  - scales

jobs:
  include:
    - stage: Deploy
      if: branch = dev AND type != pull_request
      script: tools/travis_deploy.sh igraph_*.tar.gz
      r: release

notifications:
  email:
    on_success: change
    on_failure: change
